name: Test Pipeline

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-v9

jobs:
  docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
